### ISSUE TITLE
Geoserver - checklist

### ISSUE THREAD

**Issue by CL-SHLOMIKONCHA** [MapColonies/GEEDocker#38]
- [x] check if the coordinates in the 2x1 gpkg output is the same after export from 1x1 source
- [ ] check if Geoserver supports mixed PNG and JPEG - **Open for now, not sure if needed**

- [x]  check if Geoserver supports color masks (by range?) - ignore the black background but not the pixels on the mosaics

- [x] check if Geoserver supports external pyramid files .OVR

**Check the supports of:**

- [x] Origin Tif with .ovr - **external pyramid**

- [x] Origin Tif with **internal pyramid**

- [x] JPEG compressed Tif with .ovr - **external pyramid**

- [x] JPEG compressed Tif with **internal pyramid**

- [x] JPEG compressed Tif with no pyramid

- [ ] Ecw / Jpeg2k ? _depends on Yair , should give a file_

- [x] Seeding preformance test

**Comment by CL-SHLOMIKONCHA** [comment]
- **check if the coordinates in the 2x1 gpkg output is the same after export from 1x1 source:**
Coordinates are the same on the both 2x1 and 1x1 source file

**Comment by CL-SHLOMIKONCHA** [comment]
**- check if Geoserver supports external pyramid files .RRD & .OVR:**

- Geo-server can receive OVR files as external pyramids
- RRD files are missing for check - ask Shaziri

**Comment by CL-SHLOMIKONCHA** [comment]
check if Geoserver supports color masks (by range?) - ignore the black background but not the pixels on the mosaics:
![mosaic_configs](https://user-images.githubusercontent.com/65117898/101026265-5f3ec500-357f-11eb-99c1-d1169f22ff42.png)
