### ISSUE TITLE
Mapproxy - checklist

### ISSUE THREAD

**Issue by CL-SHLOMIKONCHA** [MapColonies/GEEDocker#40]
**Abilities:**

- [x] S3 support  - **supports only cached directory with jpeg/png tiles**

- [x]  check if Mapproxy supports color masks (by range/pixels amount?) - ignore the black background but not the pixels on the mosaics - **supports transparent color and tolerance by [WMS](https://mapproxy.org/docs/nightly/sources.html) only , fixed by masking (by alpha) on origin file before publish it**
- [x] upscale/downscale by zoom levels
- [x] manage layer render's order
- [x] create a Mosaic (optimized configurations) WMS support
- [x] create a Mosaic (optimized configurations) WMTS support
- [x] update Mosaic
- [x]  check if the coordinates in the 2x1 tiling-scheme output is the same after export from 1x1 tiling-scheme source

**GET Response per tile performance:**

- [x]  WMS
- [x] WMTS

**Comment by CL-SHLOMIKONCHA** [comment]
**Performance results**

Local gpkg:
![geoserver_performance_results_img](https://user-images.githubusercontent.com/65117898/102760685-8c141a00-437e-11eb-9055-00b2add320fc.png)
